### PR TITLE
Backport MR27 - EAS

### PR DESCRIPTION
**Pull request by Flamefire**
This backports https://github.com/whatawurst/android_device_sony_yoshino-common/pull/27

CC @shank03

### CODE REVIEW

**Comment by shank03** [comment]
I am not sure about these EAS stuffs. I wasn't active that time to look through these.

Sorry :(

**Comment by Flamefire** [comment]
@linckandrea If you got some time and don't mind taking a look if these backports of your original commits to LOS 17.1 make sense it'd be very much appreciated! (Testing myself but I'm not too experienced with that part)

**Comment by linckandrea** [comment]
from a quick look everything seems ok, except

you should remove [powerstats](https://github.com/Flamefire/android_device_sony_yoshino-common/blob/MR27/platform/hardware.mk#L133)(perfmgr take in account only stats from pixelstatsHAL)

you missed these two commits
 https://github.com/linckandrea/android_device_sony_yoshino-common/commit/e0a380b09ca1651589855424ff62055d7a11ceea
 https://github.com/linckandrea/android_device_sony_yoshino-common/commit/223a2cab2f0ae47e9a82ef7ca8a5fb60ed2ad284
 
 
 if you're going to use this dt only for lilac you suggest you to tune down gpu boost freqs since is a little bit too overkilll for a hd screen
 
 EDIT: don't forget kernel commits

**Comment by Flamefire** [comment]
Thanks for taking a look!

> you should remove powerstats(perfmgr take in account only stats from pixelstatsHAL)

Ok, I added that earlier because logcat showed that it was looking for that but did not find it. Can this cause issues?

> you missed these two commits

How important are those? There have been many PRs to the upstream repo and to avoid conflicts and missing them I'm porting them one by one. The commits you mentioned are from PR 43 and hence in my MR43 branch. If those are required so that this works at all, I'll include those here, otherwise I'd go over the 7 remaining PRs before that first (damn, more work than I thought)

> EDIT: don't forget kernel commits

I'm already running the latest kernel from Apr, 20: https://github.com/Flamefire/android_kernel_sony_msm8998/commits/lineage-17.1 So that should be ok I guess?

> if you're going to use this dt only for lilac you suggest you to tune down gpu boost freqs since is a little bit too overkilll for a hd screen

Ok, which values would you suggest? Could this be done in the device repo? If so than this might be something for derfs lilac repos too (they have this 18.1 branch too)

**Comment by linckandrea** [comment]
> > you missed these two commits
> 
> How important are those? There have been many PRs to the upstream repo and to avoid conflicts and missing them I'm porting them one by one. The commits you mentioned are from PR 43 and hence in my MR43 branch. If those are required so that this works at all, I'll include those here, otherwise I'd go over the 7 remaining PRs before that first (damn, more work than I thought)
> 
thet're quite important for performaces(at microscopic level) and since you use 18.1 kernel you need this too
https://github.com/linckandrea/android_device_sony_yoshino-common/commit/27671ccac238f4ebedbc36d3ee02a42000d62c54

> > if you're going to use this dt only for lilac you suggest you to tune down gpu boost freqs since is a little bit too overkilll for a hd screen
> 
> Ok, which values would you suggest? Could this be done in the device repo? If so than this might be something for derfs lilac repos too (they have this 18.1 branch too)

lower for sure,  you can try by decreasing each gpu boost values to the smaller step

es: 312 --> 257, etc.

and yeah i was think that too, maybe adding something like a flag followed by an ifeq condition in platform/config_files.mk

**Comment by Flamefire** [comment]
Ok thanks, then I'll try to merge MR43 next and open an issue (for now) on the GPU values, so to not forget once I'm done with the open stuff.

Unrelated question as you seem very familiar with the kernel: Logcat shows such entries every now and then:

> E lowmemorykiller: Error writing /proc/11518/oom_score_adj; errno=22

This looks like a missing SEPolicy to me for the binary from kernel/sony/msm8998/drivers/staging/android/lowmemorykiller.c or something similar (missing the usual SEPolicy denied message, so maybe some other permission is missing?) Any idea?

**Comment by Flamefire** [comment]
> you should remove powerstats(perfmgr take in account only stats from pixelstatsHAL)

Tried removing this again and getting the logcat I got before:

> I hwservicemanager: getTransport: Cannot find entry android.hardware.power.stats@1.0::IPowerStats/default in either framework or device manifest.

As far as I understand this that mock-service does nothing but avoiding this message and I've seen it used at other devices. As it is only informational I guess it can be ignored.
What do you think? Any reason for or against including it?

Besides that this PR now seemingly works, so merging this to rebase the next few PRs, starting with yours. Still grateful for any additional information here :+1: 

One minor thing showing up in logcat during boot:

> E android.hardware.power@1.3-service.yoshino: extract_stats: failed to open: /d/wlan0/power_stats Error = No such file or directory

**Comment by linckandrea** [comment]
pick this for wlan stats:
https://github.com/LineageOS/android_device_fxtec_pro1/commit/6f3b986a000f3e7d62da6c253fba68590a8ad61a#diff-
f815d9c642d9f6212524ea652bd36b6c27550736bd42882273f8516fd349c52e

**Comment by Flamefire** [comment]
Thanks, that pointed me into the right direction. Before applying this I rechecked the device and that path is available and the data looks valid. So I guess the perfmgr just queries it to early. Checking the code I see that the error is kinda handled. In particular it allocates a `PowerStateSubsystem` struct and leaves it unchanged on error.
Given the description in `types.hal` this looks correct. For the contained vector:

> Vector of size zero implies either the info is not available or [...]

However I think the `name` field still needs to be set (as in https://github.com/whatawurst/android_device_sony_yoshino-common/blob/fbf067cf5cdb92cc965124c61aacbc899f766a73/hardware/power-libperfmgr/Power.cpp#L293) or the status shouldn't return "success". But in practice this seems to be ignored anyway when the states-vector is empty. Usually...
I'll fix that later

**Comment by linckandrea** [comment]
> > > you missed these two commits
> > 
> > 
> > How important are those? There have been many PRs to the upstream repo and to avoid conflicts and missing them I'm porting them one by one. The commits you mentioned are from PR 43 and hence in my MR43 branch. If those are required so that this works at all, I'll include those here, otherwise I'd go over the 7 remaining PRs before that first (damn, more work than I thought)
> 
> thet're quite important for performaces(at microscopic level) and since you use 18.1 kernel you need this too
> [linckandrea@27671cc](https://github.com/linckandrea/android_device_sony_yoshino-common/commit/27671ccac238f4ebedbc36d3ee02a42000d62c54)
> 
> > > if you're going to use this dt only for lilac you suggest you to tune down gpu boost freqs since is a little bit too overkilll for a hd screen
> > 
> > 
> > Ok, which values would you suggest? Could this be done in the device repo? If so than this might be something for derfs lilac repos too (they have this 18.1 branch too)
> 
> lower for sure, you can try by decreasing each gpu boost values to the smaller step
> 
> es: 312 --> 257, etc.
> 
> and yeah i was think that too, maybe adding something like a flag followed by an ifeq condition in platform/config_files.mk

something like this
yoshino-common:
https://github.com/linckandrea/android_device_sony_yoshino-common/commit/8c4e674c1b0c97bfac1099791ea8a8f6de9b239d

lilac:
https://github.com/linckandrea/android_device_sony_lilac/commit/e401f127ec808c055aaff94e0c92e1186291edb8

https://github.com/linckandrea/android_device_sony_lilac/commit/67eb63926637d93585becd6e25acba37b0af0afa

**Comment by Flamefire** [comment]
Thanks a lot! Imported and will be testing this

**Pull request merged**
