### PR TITLE
Backport MR 14 & MR 16

### PR DESCRIPTION
**Pull request by Flamefire**
This backports https://github.com/whatawurst/android_device_sony_yoshino-common/pull/14 and https://github.com/whatawurst/android_device_sony_yoshino-common/pull/16 (1 commit) to LOS 17.1 with some exclusions to make it work for Android 10.

Taken from #1 with reverts removed (@shank03)
Closes #1

The following commits were not taken from the original MR as they do not apply on LOS 17.1/Android 10

> yoshino-common: sepolicy: Label /persist
> yoshino-common: Remove hostapd hidl entry from manifest.xml
> yoshino-common: Remove IWifi hidl entry from manifest.xml
> yoshino-common: Move wpa_supplicant VINTF definition to wpa_supplicant module
> yoshino-common: Remove usb hidl entry from manifest.xml
> yoshino-common: Drop sepolicy version from manifest
> yoshino-common: Move supplicant service init to wpa_supplicant
> yoshino-common: Build new aidl qti power HAL
> yoshino-common: Enable v1.3 clearkey drm plugin
> yoshino-common: Exclude lineage-sdk overlays from RRO
> yoshino-common: Remove vintf entries that are now fragments
> yoshino-common: sepolicy: Re-label dpmd binary
> yoshino-common: sepoliocy: Allow platform_app to read camera prop
> yoshino-common: sepolicy: Allow system server to read camera prop
> yoshino-common: sepolicy: Allow zygote to read camera prop
> yoshino-common: sepolicy: Add policy for dpmwrapper socket
> yoshino-common: sepolicy: Allow system server to read reboot props
> Revert "yoshino-common: Exclude lineage-sdk overlays from RRO"
> yoshino-common: Add TetheringOverlay
> yoshino-common: TetheringOverlay: Disable BPF
> libc: Force build scudo free 32 bit variant of libc.
> yoshino-common: Enforce RRO for all resource overlays
> yoshino-common: Exclude FlipFlap overlays from RRO

Additionally added: 
- "hidl: build power stats hal" (avoid "Cannot find entry android.hardware.power.stats..." error)
- "Include updated overlay values for WIFI and Tethering" (LOS 17.1 build system doesn't has the nice macro for using RROs easily)

This seemingly works so far without problems

### CODE REVIEW

**Comment by shank03** [comment]
All seems good, but I suspect few commits, such as:
- RRO commits
- libc32 variant (iirc it was added in android 11 for system to support old stock blobs, don't think it's required in android 10. But if it doesn't make any difference, no need to remove)

**Comment by Flamefire** [comment]
You mean https://github.com/Flamefire/android_device_sony_yoshino-common/pull/2/commits/62a255f3a6c5bc236d9aa24e3dca69169302c122 ? TBH I'm not sure what that actually does, could you enlighten me here? I ported the 2 RROs added to the (original) overlays in https://github.com/Flamefire/android_device_sony_yoshino-common/pull/2/commits/1d4bb846a3ff75b8344073a433bf78851c92151b so the settings are there.

With the libc32 variant you are right, that option is not present in the repo at all. I removed the commit, thanks

**Comment by shank03** [comment]
I am not sure either but android developer portal has documentation (too lazy to read it :P), but iirc it was also some android 11 addition. Maybe try it, and if it doesn't work then revert all RRO commits

**Comment by Flamefire** [comment]
Couldn't find anything what "enforcing" an RRO target means. All I found is https://source.android.com/devices/architecture/rros on RROs and https://android.googlesource.com/platform/build/+/1b22428%5E%21/ which introduced that and has a comment "Enforce to generate all RRO packages for modules having resource overlays."

Err yeah, what? :D

From the code this changes (I think) putting everything into static_resource_overlays or putting somethings into static_resource_overlays and some into runtime_resource_overlays_[product/vendor]. So I guess this might mean https://github.com/Flamefire/android_device_sony_yoshino-common/pull/2/commits/6b996c1a15bc496c4e785d311d5d3a63e95d1c02 will have no effect now as it would need to be an RRO.

How can I test that? I searched for an ADB command to print the resource values but haven't found any. But there must be something I can "simply" check as that stuff influences wifi etc.

**Comment by shank03** [comment]
Unfortunately, even derf had few tough times with it. He had to redo, undo and rebuild to get the right RRO configs working. Since they were never in android 10, I wouldn't keep it.

**Comment by Flamefire** [comment]
Yeah noticed that. I'm just hesitant because Android 10 supports RROs, although not as well as 11.
Do you know how he checked, that the configs were working? I'm a bit curious here and would like to double-check that all is as I think it is/should be.
CCing @derfelot

**Comment by shank03** [comment]
> Do you know how he checked, that the configs were working? I'm a bit curious here and would like to double-check that all is as I think it is/should be.

He checked it through the availability of carrier configs and some wifi stuffs. Carrier configs weren't applied or wasn't available when something was messed up.

**Comment by Flamefire** [comment]
Did a quick test by adding a print/log into the framework and even with the current state the new wifi params are used. So no idea what those RRO settings do ;D
I think I'll remove them anyway, just to be safe

**Comment by Flamefire** [comment]
Merging this now, but keeping the revert commit for the RRO. In case anyone wants to add any information please do so!

**Pull request merged**
