### PR TITLE
Backport PR 14

### PR DESCRIPTION
**Pull request by Flamefire**
This backports https://github.com/whatawurst/android_device_sony_yoshino-common/pull/14/ to LOS 17.1 with some reverts to make it work for Android 10.

State: Testing

### CODE REVIEW

**Comment by Flamefire** [comment]
@shank03 Would you be willing to help maintaining an Android 10 version of LOS? I'd certainly could need some help by someone double-checking those backports I do. 
What I basically do: Backport each PR against the LOS 18.1 branch to my 17.1 branch (see this PR and my other MR* branches) but need to make sure the other 2 repos are kept in sync (done now) and not using Android 11 or LOS 18 features/changes
Would love to get the EAS changes in to improve battery life but also don't want to miss out on the other fixes/improvements. Also keeping Android 10 allows to keep the Sony camera which is a big plus.
I finished porting all PRs and revert the "wrong" commits (i.e. not for Android 10) and start testing each one by one now, but if you see something wrong already that would save quite some time. The base are my https://github.com/whatawurst/android_device_sony_yoshino-common/pull/42 and related PRs which I already tested to work and which contain the most important changes already as far as I could tell

**Comment by shank03** [comment]
> @shank03 Would you be willing to help maintaining an Android 10 version of LOS? I'd certainly could need some help by someone double-checking those backports I do.

Of course I can help you whenever I get free. But boy, that's a lot of commits right there XD

**Comment by Flamefire** [comment]
>  But boy, that's a lot of commits right there XD

This is only the first PR. Took me quite some time to backport all those commits.

Created #2 where I removed the reverts and their original commits so the history becomes smaller. That's probably easier but it might make sense to check the reverted commits explicitly.

What do you think?

**Comment by shank03** [comment]
Sorry for late, I was asleep and also I have checked it there

**Comment by Flamefire** [comment]
No problem, async communication here, so answer whenever you feel like ;) Especially ATM working hours likely don't match anyway. ;)

**Pull request closed without merging**
