### PR TITLE
Build in-tree display HAL

### PR DESCRIPTION
**Pull request by Flamefire**
CC @shank03 Seems to be working fine. :)

1 PR each in vendor and device repos required

### CODE REVIEW

**Comment by shank03** [comment]
I doubt how it's working.

You skipped
> Drop pre-built gralloc and libqdMetaData

Which means it's already being copied to vendor. Then why built in-tree Hal ?

If so then you should've added that ^ skipped commit too

**Comment by Flamefire** [comment]
That's the 2 other PRs I was referring too: https://github.com/Flamefire/android_device_sony_lilac/pull/4 & https://github.com/Flamefire/android_vendor_sony_lilac/pull/4

That's what you meant, wasn't it? :)

**Comment by shank03** [comment]
Oh you didn't cc.. I didn't notice. Okay then.. good to go 🚀

EDIT: Might wanna check last commit, if the change of that flag was made in respect to build system or android version.

**Comment by Flamefire** [comment]
> Oh you didn't cc.. I didn't notice. Okay then.. good to go rocket

Oh, ok. Then you might have missed https://github.com/Flamefire/android_device_sony_lilac/pull/3 & https://github.com/Flamefire/android_vendor_sony_lilac/pull/3 too? But you've seen that I skipped that gralloc commit... Yeah anyway ;D

> EDIT: Might wanna check last commit, if the change of that flag was made in respect to build system or android version.

You mean https://github.com/Flamefire/android_device_sony_yoshino-common/pull/19/commits/dfb941887df0e4d682f547c4c37e5f88917677da?
Yes, LOCAL_COPY_HEADERS was deprecated in Android 11 build system and LOS updated the sources to not need it. However in LOS 17.1 they still need it because they forgot to mention some headers and/or header-dependencies so without that revert the build won't find the gralloc_privat.h for example. The respective commits are split into 3 repositories and it seems they don't really do much about LOS 17.1 anymore. Hence I chose the easy way ;)

**Comment by shank03** [comment]
🚀

**Pull request merged**
